name: ubuntu modules (matmake + clang)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install clang
      run: wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh &&  sudo ./llvm.sh 16
    - name: Install dependencies
      run: sudo apt update && sudo apt install libsdl2-dev libc++-16-dev libc++abi-16-dev ninja-build
    - name: clone matmake3
      run: git clone https://github.com/mls-m5/matmake3 /tmp/matmake3
    - name: build matmake3
      run: cmake . && cmake --build .
      working-directory: /tmp/matmake3
    - name: build
      run: /tmp/matmake3/matmake3 --link -lSDL2 --link -lGL -j 1 --debug --flag "-DGL_GLEXT_PROTOTYPES=1 -DGL3_PROTOTYPES=1 -I/usr/include/SDL2/"
